# This file was *autogenerated* from the file rsa.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_1024 = Integer(1024); _sage_const_16 = Integer(16)##

bits = _sage_const_1024 
p	= random_prime(_sage_const_2 **bits);	print "      p = %d" %p
q	= random_prime(_sage_const_2 **bits);	print "      q = %d" %q
N	= p * q;			print "      N = p * q = %d" %N
phi	= (p - _sage_const_1 )*(q - _sage_const_1 );		print " phi(N) = (p - 1)*(q - 1) = %d" %phi
e	= _sage_const_2 **_sage_const_16  + _sage_const_1 ;			print "      e = 2^16 + 1 = %d" %e
d	=  xgcd(e, phi)[_sage_const_1 ] % phi;	print "      d = e^-1 mod phi(N) = %d" %d


print "%x" %(_sage_const_2 **(bits*_sage_const_2 ))
print "%x" %N
v = _sage_const_2 **(bits*_sage_const_2 ) - N; print "%x" %v
